### ISSUE TITLE
Grammar-Nazi

### ISSUE THREAD

**Issue by Plackpegasus** [AlexanderWyss/DiscordBot#1]
### I de Command-Description:

- **Repeat** the current playlist **infinitely**
- **Repeat** the current Song **infinitely** 
- Shows a Music-**Control**-Panel
- All commands are case **insensitive**....
- If **he's** quiet, he probably.... (s'komma hani ned fett chönne mache)

Weis ned wieso ich das um die ziit mache....

**Comment by AlexanderWyss** [comment]
:D 
Wetsch ned no pull request mache.

**Comment by AlexanderWyss** [comment]
Done

**Comment by AlexanderWyss** [comment]
Command !repeat and !repeatSong is still wrong.

**Comment by AlexanderWyss** [comment]
Done, now for real
